"""empty message

Revision ID: 18c3e4ac7c46
Revises: df7babc4193e
Create Date: 2023-09-10 21:35:15.030553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c3e4ac7c46'
down_revision = 'df7babc4193e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mainDeck', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('extraDeck', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sideDeck', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('sideDeck')
        batch_op.drop_column('extraDeck')
        batch_op.drop_column('mainDeck')

    # ### end Alembic commands ###
